### ISSUE TITLE
Build fails: Error: undefined identifier No, did you mean overloadset to?

### ISSUE THREAD

**Issue by andre2007** [symmetryinvestments/influx-d#40]
```dub build``` will fail with error message:

> ..\..\AppData\Local\dub\packages\vibe-core-1.4.3\vibe-core\source\vibe\core\core.d(692,70): Error: undefined identifier No, did you mean overloadset to?

Issue can be solved by executing command ```dub upgrade``` (Issue is caused by dub.selections.json).
As far as I remember, you include them for applications but not for libraries.

**Comment by atilaneves** [comment]
I just tried both `dub build` and `dub test` with dmd 2.088.0 and it worked fine.

> As far as I remember, you include them for applications but not for libraries.

I've read that before but have no idea why that'd be the case.

**Comment by andre2007** [comment]
@atilaneves Today it works also for me. What I can see is, today dub fetched vibe-core 1.6.2 instead of 1.4.3. It is really strange Dub fetched version 1.4.3 last time I tried because 1.6.2 is listed in dub.selections.json sind a few months.
